apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: concentric
  name: backend-deployment

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: backend
          image: $ECR_REPOSITORY:1.47
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
          - containerPort: 8080
      terminationGracePeriodSeconds: 5
