apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: concentric
  name: backend-deployment

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: backend
          image: {{506746029679.dkr.ecr.ap-northeast-2.amazonaws.com/concentric/backend}}:1.13
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
          - containerPort: 8080
      terminationGracePeriodSeconds: 5
